using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using program_ewidencyjny.Model.Domain;

namespace program_ewidencyjny.Model.InitalizationTables
{
    class CennikInitalization 

    {
        IList<Cennik> Cennik = new List<Cennik>();

      public IList<Cennik> CennikInit()
        {


            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 01.1, Nazwa = "Pelny zbior danych BDOT10k", SkNazwa = "Pełny zb.danych BDOT10k", Jednostka = "km2", Cena = 2.07, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 01.1, Nazwa = "Wybrany zbior danych BDOT10k", SkNazwa = "Wybrany zb.danych BDOT10k", Jednostka = "km2", Cena = 0.62, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 02.1, Nazwa = "Mapy topograficzne w skalach 1:10000, 1:25000, 1:50000, 1:100000, o ktorych mowa w art. 4 ust. 1e pkt 3 w postaci rastrowej", SkNazwa = "Mapy topo. > 10k raster", Jednostka = "arkusz mapy oznaczony jednym godłem", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 02.2, Nazwa = "Mapy topograficzne w skalach 1:250000, 1:500000, 1:1000000, o ktorych mowa w art. 4 ust. 1e pkt 3 w postaci rastrowej", SkNazwa = "Mapy topo. > 25k raster", Jednostka = "arkusz mapy oznaczony jednym godłem", Cena = 25.89, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 02.3, Nazwa = "Mapy topograficzne w skalach 1:10000, 1:25000, 1:50000, 1:100000, o ktorych mowa w art. 4 ust. 1e pkt 3 w postaci wektorowej", SkNazwa = "Mapy topo. > 10k wektor", Jednostka = "arkusz mapy oznaczony jednym godłem", Cena = 25.89, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 02.4, Nazwa = "Mapy topograficzne w skalach 1:250000, 1:500000, 1:1000000, o ktorych mowa w art. 4 ust. 1e pkt 3 w postaci wektorowej", SkNazwa = "Mapy topo. > 25k wektor", Jednostka = "arkusz mapy oznaczony jednym godłem", Cena = 25.89, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 02.5, Nazwa = "Mapy topograficzne w skalach 1:250000, 1:500000, 1:1000000, o ktorych mowa w art. 4 ust. 1e pkt 3 w postaci drukowanej", SkNazwa = "Mapy topo. > 25k wydruk", Jednostka = "arkusz mapy oznaczony jednym godłem", Cena = 31.06, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 02.6, Nazwa = "Mapy topograficzne w skalach 1:250000, 1:500000, 1:1000000, o ktorych mowa w art. 4 ust. 1e pkt 3 w postaci drukowanej", SkNazwa = "Mapy topo. > 25k wydruk", Jednostka = "arkusz mapy oznaczony jednym godłem", Cena = 31.06, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 03.1, Nazwa = "Fotogrametryczne zdjęcie lotnicze", SkNazwa = "Fotog. zd. lot.", Jednostka = "zdjęcie", Cena = 12.43, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 03.2, Nazwa = "Ortofotomapa", SkNazwa = "Ortofotomapa.", Jednostka = "km2", Cena = 2.07, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 03.3, Nazwa = "Zbiór danych pomiarowych dotyczący numerycznego modelu terenu", SkNazwa = "Zb.danych pom. dot. NMT", Jednostka = "km2", Cena = 4.15, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 03.4, Nazwa = "Numeryczny model rzeźby terenu", SkNazwa = "Num. mod. rzezb. terenu", Jednostka = "km2", Cena = 2.07, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 03.5, Nazwa = "Numeryczny model pokrycia terenu", SkNazwa = "Num. mod. pokr. terenu.", Jednostka = "km2", Cena = 2.07, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 03.6, Nazwa = "Zbiór danych dotyczący fotopunktów w postaci elektronicznej lub drukowanej", SkNazwa = "Zb. dan. dot. fotopunktów", Jednostka = "fotopunkt", Cena = 0.2, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 04.1, Nazwa = "Zbiór danych PRPOG", SkNazwa = "Zbiór danych PRPOG", Jednostka = "punkt osnowy", Cena = 15.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 04.2, Nazwa = "Wykazy danych charakterystycznych dla podstawowej osnowy", SkNazwa = "Wyk. dan.char. podst.osn.", Jednostka = "punkt osnowy", Cena = 7.24, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 04.3, Nazwa = "Mapa lub szkic przeglądowy podstawowej osnowy geodezyjnej, grawimetrycznej lub magnetycznej", SkNazwa = "Map. lub szk. podst. osn.", Jednostka = "punkt osnowy", Cena = 2.07, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 04.4, Nazwa = "Opis topograficzny podstawowej osnowy geodezyjnej, grawimetrycznej lub magnetycznej", SkNazwa = "Opis podst. osn", Jednostka = "punkt osnowy", Cena = 5.18, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 04.5, Nazwa = "Inne niż satelitarne dane obserwacyjne podstawowej osnowy geodezyjnej, grawimetrycznej lub magnetycznej", SkNazwa = "In.niż sat. dan. obs.", Jednostka = "punkt osnowy", Cena = 7.24, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 04.6, Nazwa = "Satelitarne dane obserwacyjne podstawowej osnowy geodezyjnej", SkNazwa = "Sat. dan. obs.", Jednostka = "punkt osnowy", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 05.1, Nazwa = "Zbiór danych BDSOG", SkNazwa = "Zbiór danych BDSOG", Jednostka = "punkt osnowy", Cena = 15.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 05.2, Nazwa = "Wykaz współrzędnych i wysokości punktów szczegółowej osnowy geodezyjnej", SkNazwa = "Wyk.wspol. szczeg.osn.", Jednostka = "punkt osnowy", Cena = 7.24, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 05.3, Nazwa = "Opis topograficzny szczegółowej osnowy geodezyjnej", SkNazwa = "Opis szcz.osn", Jednostka = "punkt osnowy", Cena = 5.18, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 05.4, Nazwa = "Mapa lub szkic przeglądowy szczegółowej osnowy geodezyjnej", SkNazwa = "Mapa lub szkic szcz. osn.", Jednostka = "punkt osnowy", Cena = 2.07, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 06.1, Nazwa = "Zbiór danych K-GESUT", SkNazwa = "Zbiór danych K-GESUT", Jednostka = "km2", Cena = 1.04, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 06.2, Nazwa = "Wybrany zbiór danych K-GESUT", SkNazwa = "Wyb. zb. danych K-GESUT", Jednostka = "km2", Cena = 0.31, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 07.1, Nazwa = "Pełny zbiór danych GESUT", SkNazwa = "Pel. zb, dan. GESUT", Jednostka = "ha", Cena = 15.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 07.2, Nazwa = "Wybrany zbiór danych GESUT", SkNazwa = "Wyb. zb. dan. GESUT", Jednostka = "ha", Cena = 4.15, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 08.1, Nazwa = "Pełny zbiór danych BDOT500", SkNazwa = "Pel. zb. dan. BDOT500", Jednostka = "ha", Cena = 20.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 08.2, Nazwa = "Wybrany zbiór danych BDOT500", SkNazwa = "Wyb. zb. dan. BDOT500", Jednostka = "ha", Cena = 5.18, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.1, Nazwa = "Zbiór danych bazy danych EGiB", SkNazwa = "Zb. dan. EGiB", Jednostka = "ha", Cena = 31.06, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.2, Nazwa = "Zbiór danych bazy danych EGiB - dotyczący punktów granicznych", SkNazwa = "Zb. dan. EGiB -pkt.gr", Jednostka = "punkt graniczny", Cena = 1.04, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.31, Nazwa = "Zbiór danych bazy danych EGiB dotyczących działek ewidencyjnych albo budynków albo lokali", SkNazwa = "Zb. dan. EGiB dz/bud", Jednostka = "plot albo budynek", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.32, Nazwa = "Zbiór danych bazy danych EGiB dotyczących działek ewidencyjnych albo budynków albo lokali", SkNazwa = "Zb. dan. EGiB/lok", Jednostka = "lokal", Cena = 3.11, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.4, Nazwa = "Zbiór danych bazy danych EGiB dotyczących konturów użytków gruntowych", SkNazwa = "Zb. dan. EGiB kont.uzyt.", Jednostka = "kontur uzytku gruntowego", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.5, Nazwa = "Zbiór danych bazy danych EGiB dotyczących konturów klasyfikacyjnych", SkNazwa = "Zb. dan. EGiB kont.kl.", Jednostka = "kontur klasyfikacyjny", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.6, Nazwa = "Zbiór danych bazy danych EGiB dotyczący podmiotów wykazanych w ewidencji gruntów i budynków", SkNazwa = "Zb. dan. EGiB podmiot", Jednostka = "Podmiot-osoba lub jedn. organizacyjna", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 09.7, Nazwa = "Zbiór danych bazy danych EGiB dotyczących innych obiektów EGiB ( niewymienionych w l.p.2-6)", SkNazwa = "Zb. dan. EGiB inne", Jednostka = "obiekt bazy danych EGiB", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.1, Nazwa = "Kopia arkusza mapy ewidencyjnej gruntów i budynków w postaci drukowanej", SkNazwa = "Kop.ark.mapy ewid", Jednostka = "Arkusz formatu A0", Cena = 72.47, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.2, Nazwa = "Następna kopia arkusza mapy ewidencyjnej gruntów i budynków w postaci drukowanej o którym mowa w l.p. 1, wykonywana w ramach tego samego zamówienia", SkNazwa = "Nast. kop.ark.map.ewid.", Jednostka = "Arkusz formatu A0", Cena = 41.41, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.3, Nazwa = "Mapa ewidencji gruntów i budynków w postaci wektorowej", SkNazwa = "Mapa EGIB wektor.", Jednostka = "ha", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.4, Nazwa = "Mapa ewidencji gruntów i budynków w postaci rastrowej", SkNazwa = "Mapa EGiB raster.", Jednostka = "ha", Cena = 6.21, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.5, Nazwa = "Kopia rejestru gruntów w postaci drukowanej", SkNazwa = "Kop. rej. grunt. druk.", Jednostka = "obręb ewidencyjny", Cena = 1035.3, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.6, Nazwa = "Kopia rejestru gruntów w postaci elektronicznej", SkNazwa = "Kop. rej. grunt. elek.", Jednostka = "obręb ewidencyjny", Cena = 724.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.7, Nazwa = "Kopia kartoteki budynków w granicach miasta w postaci drukowanej", SkNazwa = "Kop.kart.bud.druk.mi", Jednostka = "obręb ewidencyjny", Cena = 1035.3, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.8, Nazwa = "Kopia kartoteki budynków w granicach obszaru wiejskiego w postaci drukowanej", SkNazwa = "Kop.kart.bud.druk.wi", Jednostka = "obręb ewidencyjny", Cena = 621.18, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.9, Nazwa = "Kopia kartoteki budynków w granicach miasta w postaci elektronicznej", SkNazwa = "Kop.kart.bud.elek.mi", Jednostka = "obręb ewidencyjny", Cena = 724.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.10, Nazwa = "Kopia kartoteki budynków w granicach obszaru wiejskiego w postaci elektronicznej", SkNazwa = "Kop.kart.bud.elek.wi", Jednostka = "obręb ewidencyjny", Cena = 414.12, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.11, Nazwa = "Kopia rejestru budynków w granicach miasta w postaci drukowanej", SkNazwa = "Kop.rej.bud.druk.mia", Jednostka = "obręb ewidencyjny", Cena = 207.06, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.12, Nazwa = "Kopia rejestru budynków w granicach obszaru wiejskiego w postaci drukowanej", SkNazwa = "Kop.rej.bud.druk.wie", Jednostka = "obręb ewidencyjny", Cena = 20.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.13, Nazwa = "Kopia rejestru budynków w granicach miasta w postaci elektronicznej", SkNazwa = "Kop.rej.bud.elek.mia", Jednostka = "obręb ewidencyjny", Cena = 155.3, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.14, Nazwa = "Kopia rejestru budynków w granicach obszaru wiejskiego w postaci elektronicznej", SkNazwa = "Kop.rej.bud.elek.wie", Jednostka = "obręb ewidencyjny", Cena = 15.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.15, Nazwa = "Kopia rejestru lub kartoteki lokali w granicach miasta w postaci drukowanej", SkNazwa = "Kop.r/k.lok.druk.mia", Jednostka = "obręb ewidencyjny", Cena = 724.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.16, Nazwa = "Kopia rejestru lub kartoteki lokali w granicach obszaru wiejskiego w postaci drukowanej", SkNazwa = "Kop.r/k.lok.druk.wie", Jednostka = "obręb ewidencyjny", Cena = 103.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.17, Nazwa = "Kopia rejestru lub kartoteki lokali w granicach miasta w postaci elektronicznej", SkNazwa = "Kop.r/k.lok.elek.mia", Jednostka = "obręb ewidencyjny", Cena = 517.65, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.18, Nazwa = "Kopia rejestru lub kartoteki lokali w granicach obszaru wiejskiego w postaci elektronicznej", SkNazwa = "Kop.r/k.lok.elek.wie", Jednostka = "obręb ewidencyjny", Cena = 72.47, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.19, Nazwa = "Wykaz (skorowidz) działek ewidencyjnych", SkNazwa = "Wykaz działek ewid", Jednostka = "Działka ewidencyjna w granicach jednego obrębu", Cena = 0.25, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.20, Nazwa = "Wykaz podmiotów, ujawnionych w bazie danych ewidencji gruntów  i budynków", SkNazwa = "Wykaz podmiotów", Jednostka = "Osoba lub inny podmiot", Cena = 0.42, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.211, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci elektronicznej", SkNazwa = "Wyk/zst zb.el gmin", Jednostka = "Gmina", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.212, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci elektronicznej", SkNazwa = "Wyk/zst zb.el powiat", Jednostka = "Powiat", Cena = 20.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.213, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci elektronicznej", SkNazwa = "Wyk/zst zb.el wojew", Jednostka = "Województwo", Cena = 41.41, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.214, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci elektronicznej", SkNazwa = "Wyk/zst zb.el kraj", Jednostka = "Kraj", Cena = 82.82, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.221, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci drukowanej", SkNazwa = "Wyk/zst druk gmina", Jednostka = "Gmina", Cena = 20.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.222, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci drukowanej", SkNazwa = "Wyk/zst druk powiat", Jednostka = "Powiat", Cena = 31.06, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.223, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencją gruntów i budynków w postaci drukowanej", SkNazwa = "Wyk/zst druk wojew", Jednostka = "Województwo", Cena = 51.77, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 10.224, Nazwa = "Wykazy albo zestawienie zbiorcze danych objętych ewidencjš gruntów i budynków w postaci drukowanej", SkNazwa = "Wyk/zst druk kraj", Jednostka = "Kraj", Cena = 103.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.1, Nazwa = "Wypis z rejestru gruntów w postaci dokumentu elektronicznego", SkNazwa = "Wypis z RG elektron.", Jednostka = "Jednostka rejestrowa gruntów", Cena = 40, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.2, Nazwa = "Wypis z rejestru gruntów w postaci dokumentu drukowanego", SkNazwa = "Wypis z RG druk.", Jednostka = "Jednostka rejestrowa gruntów", Cena = 50, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.3, Nazwa = "Wypis z rejestru gruntów bez danych osobowych w postaci dokumentu elektronicznego", SkNazwa = "Wypis z RG bez os.el", Jednostka = "Jednostka rejestrowa gruntów", Cena = 24, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.4, Nazwa = "Wypis z rejestru gruntów bez danych osobowych w postaci dokumentu drukowanego", SkNazwa = "Wypis z RG bez os.dr", Jednostka = "Jednostka rejestrowa gruntów", Cena = 30, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.5, Nazwa = "Wypis z rejestru gruntów oraz wyrys z mapy ewidencyjnej w postaci dokumentu elektronicznego", SkNazwa = "Wypis z RG wyrys ele", Jednostka = "Jednostka rejestrowa gruntów", Cena = 140, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.6, Nazwa = "Wypis z rejestru gruntów oraz wyrys z mapy ewidencyjnej w postaci dokumentu drukowanego", SkNazwa = "Wypis z RG wyrys dru", Jednostka = "Jednostka rejestrowa gruntów", Cena = 150, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.7, Nazwa = "Wyrys z mapy ewidencyjnej w postaci dokumentu elektronicznego", SkNazwa = "Wyrys z m.ewid.elekt", Jednostka = "Jednostka rejestrowa gruntów", Cena = 105, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.8, Nazwa = "Wyrys z mapy ewidencyjnej w postaci dokumentu drukowanego", SkNazwa = "Wyrys z m.ewid.druk ", Jednostka = "Jednostka rejestrowa gruntów", Cena = 110, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.9, Nazwa = "Wypis z rejestru budynków albo wypis z rejestru lokali w postaci dokumentu elektronicznego", SkNazwa = "Wypis z RBL elektr. ", Jednostka = "Jednostka rejestrowa budynków albo jednostka rejestrowa lokali", Cena = 25, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.10, Nazwa = "Wypis z rejestru budynków albo wypis z rejestru lokali w postaci dokumentu drukowanego", SkNazwa = "Wypis z RBL druk ", Jednostka = "Jednostka rejestrowa budynków albo jednostka rejestrowa lokali", Cena = 30, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.11, Nazwa = "Wypis z kartoteki budynków albo wypis z kartoteki lokali w postaci dokumentu elektronicznego", SkNazwa = "Wypis z KBL elektr ", Jednostka = "Pozycja kartoteki budynków albo pozycja kartoteki lokali", Cena = 15, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.12, Nazwa = "Wypis z kartoteki budynków albo wypis z kartoteki lokali w postaci dokumentu drukowanego", SkNazwa = "Wypis z KBL druk.", Jednostka = "Pozycja kartoteki budynków albo pozycja kartoteki lokali", Cena = 20, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.13, Nazwa = "Uproszczony wypis z rejestru gruntów (bez adnotacji dotyczących jakoci danych ewidencyjnych oraz klauzuli upoważniającej do oznaczenia nieruchomoci w księdze wieczystej na podstawie tego dokumentu)", SkNazwa = "Uproszczony wypis", Jednostka = "Działka ewidencyjna", Cena = 15, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.14, Nazwa = "Wypis z wykazu działek", SkNazwa = "Uproszczony wypis", Jednostka = "Działka ewidencyjna", Cena = 5, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 11.15, Nazwa = "Wypis z wykazu podmiotów", SkNazwa = "Wypis z wyk.podm.", Jednostka = "Podmiot (osoba lub instytucja)", Cena = 5, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 12.1, Nazwa = "Zbiór danych rejestru cen i wartoci nieruchomoci w postaci elektronicznej", SkNazwa = "Zb.dan.rej.cen.i.war ", Jednostka = "nieruchomoć będąca przedmiotem transakcji albo wyceny", Cena = 6.21, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 12.2, Nazwa = "Wyciąg z rejestru cen i wartoci nieruchomoci w postaci dokumentu drukowanego", SkNazwa = "Wyc.z.rej.cen.druk ", Jednostka = "nieruchomoć będąca przedmiotem transakcji albo wyceny", Cena = 8.28, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 13.1, Nazwa = "Mapa zasadnicza w postaci rastrowej", SkNazwa = "Mapa zasadnicza rast", Jednostka = "ha", Cena = 7.24, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 13.2, Nazwa = "Mapa zasadnicza w postaci wektorowej", SkNazwa = "Mapa zasadnicza wekt", Jednostka = "ha", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 13.3,Nazwa = "Arkusz mapy zasadniczej w postaci drukowanej", SkNazwa = "Arkusz mapy zas.druk",Jednostka = "Arkusz formatu A0", Cena = 10.35, Wspolczynnik = 1 });		
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 13.4, Nazwa = "Kolejna kopia arkusza mapy zasadniczej,o którym mowa w lp. 3", SkNazwa = "Kol. kop. druk m.zas", Jednostka = "Arkusz formatu A0", Cena = 82.82, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 14.1, Nazwa = "Kartograficzne opracowania tematyczne i specjalne oraz niestandardowe opracowania topograficzne, niewymienione w tabelach nr 1-13, w postaci rastrowej", SkNazwa = "Kart.op.sp.in.top.ra", Jednostka = "arkusz mapy", Cena = 10.35, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 14.2, Nazwa = "Kartograficzne opracowania tematyczne  i specjalne oraz niestandardowe opracowania topograficzne, niewymienione w tabelach 1-13, w postaci wektorowej", SkNazwa = "Kart.op.sp.in.top.we", Jednostka = "arkusz mapy", Cena = 15.53, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 14.3, Nazwa = "Kartograficzne opracowania tematyczne  i specjalne oraz niestandardowe opracowania topograficzne, niewymienione w tabelach 1-13, w postaci drukowanej", SkNazwa = "Kart.op.sp.in.top.dr", Jednostka = "arkusz mapy", Cena = 20.71, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 15.1, Nazwa = "Opracowanie satelitarnych danych obserwacyjnych", SkNazwa = "Oprac.satel.dan.obse", Jednostka = "punkt sytuacyjny", Cena = 5.18, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 16.1, Nazwa = "Opracowanie satelitarnych danych obserwacyjnych", SkNazwa = "Oprac.satel.dan.obse", Jednostka = "punkt sytuacyjny", Cena = 5.18, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 16.2, Nazwa = "Kopia materiału zasobu innego niż wymienione w tabelach 1-15 w postaci elektronicznej", SkNazwa = "Kop.mat.zas.in elekt", Jednostka = "dokument", Cena = 7.24, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 16.3, Nazwa = "Uwierzytelnianie dokumentów opracowanych przez wykonawców prac geodezyjnych  i kartograficznych, co do zgodnoci tych dokumentów z danymi zawartymi w bazach danych, o których mowa w art. 4 ust. 1a oraz 1b ustawy, lub z dokumentami przyjętymi do państwowego zasobu geodezyjnego i kartograficznego", SkNazwa = "Uwierzyt.dok.pierw.", Jednostka = "Pierwszy egzemplarz uwierzytelnianego dokumentu", Cena = 50, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 16.4, Nazwa = "Uwierzytelnianie dokumentów opracowanych przez wykonawców prac geodezyjnych  i kartograficznych, co do zgodnoci tych dokumentów z danymi zawartymi w bazach danych, o których mowa w art. 4 ust. 1a oraz 1b ustawy, lub z dokumentami przyjętymi do państwowego zasobu geodezyjnego i kartograficznego", SkNazwa = "Uwierzyt.dok.nast.", Jednostka = "Kolejne egzemplarze uwierzytelnianego dokumentu", Cena = 5, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 16.5, Nazwa = "Udostępnianie do wglšdu zbiorów aktów notarialnych oraz orzeczeń sšdowych i decyzji administracyjnych będšcych podstawš wpisów w ewidencji gruntów i budynków, podmiotom które posiadajš uprawnienia do " ,SkNazwa = "Udost.wgl.pods.EGiB", Jednostka = "zbiór dokumentów, dotyczšcych jednej jednostki ewidencyjnej, udostępniony na okres do 4 godzin", Cena = 30, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 16.6, Nazwa = "Uzgodnienie usytuowania projektowanej sieci uzbrojenia terenu", SkNazwa = "Uzgod.usyt.sieci uzb", Jednostka = "Projektowana sieć uzbrojenia terenu jednego rodzaju", Cena = 150, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 17.1, Nazwa = "Udostępnianie danych korekcyjnych sieciowych (RTN)", SkNazwa = "Udost. RTN", Jednostka = "1 rok udostępniania usługi", Cena = 1500, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 17.2, Nazwa = "Udostępnianie danych korekcyjnych z pojedynczej stacji referencyjnej (RTK))", SkNazwa = "Udost. RTK", Jednostka = "1 rok udostępniania usługi", Cena = 700, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 17.3, Nazwa = "Udostępnianie danych korekcyjnych różnicowych (DGPS))" ,SkNazwa = "Udost. DGPS ", Jednostka = "1 rok udostępniania usługi", Cena = 300, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 17.4, Nazwa = "Udostępnienie satelitarnych obserwacji odnoszących się do stacji referencyjnych)", SkNazwa = "Udost. stacji ref ", Jednostka = "1 rok udostępniania usługi", Cena = 1000, Wspolczynnik = 1 });
            Cennik.Add(new Cennik() { NrCennika = 2019, Pozycja = 17.5, Nazwa = "Udostępnienie satelitarnych obserwacji dla punktów o zadanych współrzędnych (wirtualnych stacji referencyjnych)", SkNazwa = "Udost. wirt.st.ref.", Jednostka = "1 rok udostępniania usługi", Cena = 1200, Wspolczynnik = 1 });

            return Cennik;
        }
    }
}
